# Generated by Django 3.2.4 on 2021-06-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0002_auto_20210605_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-pk']},
        ),
    ]
