# Generated by Django 3.2.4 on 2021-06-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagle', '0004_auto_20210607_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
